apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-app
    spec:
      containers:
      - image: temp-vpms
        name: temp-vpms
        imagePullPolicy: IfNotPresent # for local image
        resources: {}
        ports:
        - containerPort: 8000
status: {}

---
# for service for backend
apiVersion: v1
kind: Service
metadata:
  name: vpms-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30001
  selector:
    app: my-app 
